### ISSUE TITLE
Klipper App Icon is used in Systemtray on KDE 6, instead of clipboard icon.

### ISSUE THREAD

**Issue by snoweuph** [coderhisham/Futura-Icon-Pack#1]
Currently:
![image](https://github.com/coderhisham/Futura-Icon-Pack/assets/76737863/7c6a24c6-1413-4114-a84b-086b5b198dbc)

The Fix for this is pretty simple:
I just created a copy of the clipboard.svg named klipper.svg in all of the panel folder scales.
And I had to delete the klipper Icon from the apps/

after that the icon is fixed:
![image](https://github.com/coderhisham/Futura-Icon-Pack/assets/76737863/1aadb3f7-58f4-4c96-8ef3-1d56892fe177)

**Comment by coderhisham** [comment]
Thanks for your valuable feedback. The issue has been resolved.
